version: '3.8'
services:
  xiaochen-gateway:
    build: gateway
    image: xiaochen-gateway:latest
    container_name: xiaochen-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_NACOS_CONFIG_NAMESPACE: "17511c98-b7c1-4a08-bb09-2378009ff078"
      SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE: "17511c98-b7c1-4a08-bb09-2378009ff078"
      SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR: "192.168.191.121:8848"
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: "192.168.191.121:8848"
      SPRING_CLOUD_NACOS_CONFIG_USERNAME: "nacos"
      SPRING_CLOUD_NACOS_DISCOVERY_USERNAME: "nacos"
      SPRING_CLOUD_NACOS_CONFIG_PASSWORD: "nacos"
      SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD: "nacos"
  xiaochen-auth:
    build: auth
    image: xiaochen-auth:laster
    container_name: xiaochen-auth
    environment:
      SPRING_CLOUD_NACOS_CONFIG_NAMESPACE: "17511c98-b7c1-4a08-bb09-2378009ff078"
      SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE: "17511c98-b7c1-4a08-bb09-2378009ff078"
      SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR: "192.168.191.121:8848"
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: "192.168.191.121:8848"
      SPRING_CLOUD_NACOS_CONFIG_USERNAME: "nacos"
      SPRING_CLOUD_NACOS_DISCOVERY_USERNAME: "nacos"
      SPRING_CLOUD_NACOS_CONFIG_PASSWORD: "nacos"
      SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD: "nacos"
  xiaochen-monitor:
    build: monitor
    image: xiaochen-monitor:latest
    container_name: xiaochen-monitor
    environment:
      SPRING_CLOUD_NACOS_CONFIG_NAMESPACE: "17511c98-b7c1-4a08-bb09-2378009ff078"
      SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE: "17511c98-b7c1-4a08-bb09-2378009ff078"
      SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR: "192.168.191.121:8848"
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: "192.168.191.121:8848"
      SPRING_CLOUD_NACOS_CONFIG_USERNAME: "nacos"
      SPRING_CLOUD_NACOS_DISCOVERY_USERNAME: "nacos"
      SPRING_CLOUD_NACOS_CONFIG_PASSWORD: "nacos"
      SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD: "nacos"
  xiaochen-system:
    build: modules/system
    image: xiaochen-system:latest
    container_name: xiaochen-system
    environment:
      SPRING_CLOUD_NACOS_CONFIG_NAMESPACE: "17511c98-b7c1-4a08-bb09-2378009ff078"
      SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE: "17511c98-b7c1-4a08-bb09-2378009ff078"
      SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR: "192.168.191.121:8848"
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: "192.168.191.121:8848"
      SPRING_CLOUD_NACOS_CONFIG_USERNAME: "nacos"
      SPRING_CLOUD_NACOS_DISCOVERY_USERNAME: "nacos"
      SPRING_CLOUD_NACOS_CONFIG_PASSWORD: "nacos"
      SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD: "nacos"
  xiaochen-file:
    build: modules/file
    image: xiaochen-file:latest
    container_name: xiaochen-file
    environment:
      SPRING_CLOUD_NACOS_CONFIG_NAMESPACE: "17511c98-b7c1-4a08-bb09-2378009ff078"
      SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE: "17511c98-b7c1-4a08-bb09-2378009ff078"
      SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR: "192.168.191.121:8848"
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: "192.168.191.121:8848"
      SPRING_CLOUD_NACOS_CONFIG_USERNAME: "nacos"
      SPRING_CLOUD_NACOS_DISCOVERY_USERNAME: "nacos"
      SPRING_CLOUD_NACOS_CONFIG_PASSWORD: "nacos"
      SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD: "nacos"

